services:
  #https://hub.docker.com/r/linuxserver/duckdns
  duckdns:
    image: lscr.io/linuxserver/duckdns:${DUCKDNS_VERSION:-latest}
    container_name: duckdns
    hostname: duckdns
    restart: unless-stopped
    networks:
      - pihole
    ports:
      - "${DUCKDNS_PORT}:80"
    environment:
      - TZ="${TZ}"
      - PUID="${HOST_UID}"
      - PGID="${HOST_GID}"
      - SUBDOMAINS="${DUCKDNS_DOMAINS}"
      - TOKEN="${DUCKDNS_TOKEN}"
      - UPDATE_IP="ipv4"
      - LOG_FILE="false"
    volumes:
      - "${CONFIG}/duckdns:/config"
networks:
  pihole:
    name: pihole
    external: true
